config/routes.rb
Rails.application.routes.draw do
  resources :empties
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/empty.rb
class Empty < ApplicationRecord
end

app/controllers/empties_controller.rb
class EmptiesController < ApplicationController
  before_action :set_empty, only: [:show, :edit, :update, :destroy]

  # GET /empties
  # GET /empties.json
  def index
    @empties = Empty.all
  end

  # GET /empties/1
  # GET /empties/1.json
  def show
  end

  # GET /empties/new
  def new
    @empty = Empty.new
  end

  # GET /empties/1/edit
  def edit
  end

  # POST /empties
  # POST /empties.json
  def create
    @empty = Empty.new(empty_params)

    respond_to do |format|
      if @empty.save
        format.html { redirect_to @empty, notice: 'Empty was successfully created.' }
        format.json { render :show, status: :created, location: @empty }
      else
        format.html { render :new }
        format.json { render json: @empty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empties/1
  # PATCH/PUT /empties/1.json
  def update
    respond_to do |format|
      if @empty.update(empty_params)
        format.html { redirect_to @empty, notice: 'Empty was successfully updated.' }
        format.json { render :show, status: :ok, location: @empty }
      else
        format.html { render :edit }
        format.json { render json: @empty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empties/1
  # DELETE /empties/1.json
  def destroy
    @empty.destroy
    respond_to do |format|
      format.html { redirect_to empties_url, notice: 'Empty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empty
      @empty = Empty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empty_params
      params.fetch(:empty, {})
    end
end

app/helpers/empties_helper.rb
module EmptiesHelper
end

app/views/empties/_form.html.erb
<%= form_with(model: empty, local: true) do |form| %>
  <% if empty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empty.errors.count, "error") %> prohibited this empty from being saved:</h2>

      <ul>
        <% empty.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/empties/edit.html.erb
<h1>Editing Empty</h1>

<%= render 'form', empty: @empty %>

<%= link_to 'Show', @empty %> |
<%= link_to 'Back', empties_path %>

app/views/empties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empties</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empties.each do |empty| %>
      <tr>
        <td><%= link_to 'Show', empty %></td>
        <td><%= link_to 'Edit', edit_empty_path(empty) %></td>
        <td><%= link_to 'Destroy', empty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empty', new_empty_path %>

app/views/empties/new.html.erb
<h1>New Empty</h1>

<%= render 'form', empty: @empty %>

<%= link_to 'Back', empties_path %>

app/views/empties/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_empty_path(@empty) %> |
<%= link_to 'Back', empties_path %>